// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package hot

import (
	"saliva-movie/api/hot"
)

type ControllerV1 struct{}

func NewV1() hot.IHotV1 {
	return &ControllerV1{}
}
