// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package searchInto

import (
	"saliva-movie/api/searchInto"
)

type ControllerV1 struct{}

func NewV1() searchInto.ISearchIntoV1 {
	return &ControllerV1{}
}
